### ISSUE TITLE
Cannot find file './assets/fonts/Poppins-Regular.ttf'.Dependencies

### ISSUE THREAD

**Issue by jusondac** [ReenyDavidson/native-todo#1]
I got this, when I was realize that it exist on source folder structure at assets. But, expo does'nt seeing it. I run it from local, and search any probably caused by this error. but theres no explain. I hope I got an explanation by this caused. Help me!

**Comment by ReenyDavidson** [comment]
Thank you for using this and sorry for late reply. The problem is as a result of you not downloading the font package. Please go here https://fonts.google.com/specimen/Poppins to download the required font or go here https://fonts.google.com/ to download any font of your choice. If the problem persists, please get back to me.

**Comment by ReenyDavidson** [comment]
> I got this, when I was realize that it exist on source folder structure at assets. But, expo does'nt seeing it. I run it from local, and search any probably caused by this error. but theres no explain. I hope I got an explanation by this caused. Help me!

Thank you for using this and sorry for late reply. The problem is as a result of you not downloading the font package. Please go here https://fonts.google.com/specimen/Poppins to download the required font or go here https://fonts.google.com/ to download any font of your choice. If the problem persists, please get back to me.
